[default]
description = "Default permissions for the plugin"
permissions = [
	"allow-ping",
	"allow-check-accessibility-enabled",
	"allow-open-accessibility-settings",
	"allow-get-frontmost-ui-tree",
	"allow-click-node",
	"allow-perform-gesture",
	"allow-perform-global-action",
	"allow-perform-node-action",
	"allow-type-text",
]
